#!/bin/sh /etc/rc.common
# Copyright (C) 2012-2014 OpenWrt.org

START=90

USE_PROCD=1
PROG="/usr/sbin/goispappd"

start_service() {
	procd_open_instance
	procd_append_param command
	procd_close_instance
}

stop_service()
{
	# Save any pending UCI changes (credentials, device info, etc.)
	$UCI_COMMIT Device
}

service_triggers()
{
	procd_add_reload_trigger ispappd
}
