name: BUILD PACKAGES goispappd

on:
  push:
    branches:
      - main
    paths:
      - 'feeds/goispappd/*'
      - '.github/workflows/build-goipk.yml'

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

  build:
    needs: changes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      max-parallel: 10
      matrix:
        arch:
          - arm_cortex-a7_neon-vfpv4-23.05-SNAPSHOT
          # - arm_cortex-a7_vfpv4-23.05-SNAPSHOT
          # - arm_cortex-a9-23.05-SNAPSHOT
          # - mediatek-filogic-23.05-SNAPSHOT
          # - mipsel_mips32-23.05-SNAPSHOT
          # - ath79-mikrotik-23.05-SNAPSHOT
          # - mipsel_24kc-23.05-SNAPSHOT
          # - x86-generic-23.05-SNAPSHOT
          # - arm_cortex-a7-23.05-SNAPSHOT
          # - mvebu-cortexa53-23.05-SNAPSHOT
          # - x86-64-23.05-SNAPSHOT
          # - ath79-generic-23.05-SNAPSHOT
          # - mediatek-mt7622-23.05-SNAPSHOT
          # - ramips-mt76x8-23.05-SNAPSHOT
          # - ramips-mt7620-23.05-SNAPSHOT
          # - ramips-mt7621-23.05-SNAPSHOT
          # - ramips-rt288x-23.05-SNAPSHOT
          # - ramips-rt305x-23.05-SNAPSHOT
          - aarch64_generic-23.05-SNAPSHOT
          # - aarch64_cortex-a53-23.05-SNAPSHOT
          # - aarch64_cortex-a72-23.05-SNAPSHOT
          # - arm_cortex-a15_neon-vfpv4-23.05-SNAPSHOT
          # - x86_64-23.05-SNAPSHOT
          # - arm_cortex-a5_vfpv4-23.05-SNAPSHOT
          # - ipq807x-generic-23.05-SNAPSHOT
          # - ramips-rt3883-23.05-SNAPSHOT
          # - bcm47xx-mips74k-23.05-SNAPSHOT
          # - mipsel_74kc-23.05-SNAPSHOT
          # - mips_mips32-23.05-SNAPSHOT
          # - bmips-bcm63268-23.05-SNAPSHOT
          # - bmips-bcm6368-23.05-SNAPSHOT
          # - ipq40xx-mikrotik-23.05-SNAPSHOT
          # - bmips-bcm6362-23.05-SNAPSHOT
          # - i386_pentium4-23.05-SNAPSHOT
          # - mips_24kc-23.05-SNAPSHOT
          # - mips64_octeonplus-23.05-SNAPSHOT
          # - bmips-bcm6358-23.05-SNAPSHOT
          # - bmips-bcm6328-23.05-SNAPSHOT
          # - mipsel_24kc_24kf-23.05-SNAPSHOT
          # - mips_4kec-23.05-SNAPSHOT
          # - ramips-rt3883-23.05-SNAPSHOT
          # - mipsel_74kc-23.05-SNAPSHOT
          # - mediatek-mt7629-23.05-SNAPSHOT
          # - bmips-bcm6318-23.05-SNAPSHOT
          
          # new apk
          # - arm_cortex-a7_neon-vfpv4
          # - arm_cortex-a7_vfpv4
          # - arm_cortex-a9
          # - mediatek-filogic
          # - mipsel_mips32
          # - ath79-mikrotik
          # - mipsel_24kc
          # - x86-generic
          # - arm_cortex-a7
          # - mvebu-cortexa53
          # - x86-64
          # - ath79-generic
          # - mediatek-mt7622
          # - aarch64_cortex-a53
          # - aarch64_generic
          # # possible working archs for some skynet devices 
          # # end
          # - arm_cortex-a15_neon-vfpv4
          # - x86_64
          # - arm_cortex-a5_vfpv4
          # - mipsel_74kc
          # - mips_mips32
          # - i386_pentium4
          # - mips_24kc
          # - mipsel_24kc_24kf
          # - mips_4kec
          # - mipsel_74kc
          # - bcm47xx-legacy-23.05-SNAPSHOT
          # - bcm47xx-generic-23.05-SNAPSHOT
          # - sunxi-cortexa53-23.05-SNAPSHOT
          # - bcm4908-generic-23.05-SNAPSHOT
          # - bcm27xx-bcm2710-23.05-SNAPSHOT
          # - arm_cortex-a9_vfpv3-d16-23.05-SNAPSHOT
          # - armsr-armv7-23.05-SNAPSHOT
          # - lantiq-ase-23.05-SNAPSHOT
          # - bcm63xx-smp-23.05-SNAPSHOT
          # - bcm63xx-generic-23.05-SNAPSHOT
          # - realtek-rtl931x-23.05-SNAPSHOT
          # - realtek-rtl930x-23.05-SNAPSHOT
          # - realtek-rtl839x-23.05-SNAPSHOT
          # - malta-be-23.05-SNAPSHOT
          # - lantiq-xway_legacy-23.05-SNAPSHOT
          # - lantiq-xway-23.05-SNAPSHOT
          # - lantiq-xrx200-23.05-SNAPSHOT
          # - ath79-tiny-23.05-SNAPSHOT
          # - ath79-nand-23.05-SNAPSHOT
          # - at91-sama5-23.05-SNAPSHOT
          # - rockchip-armv8-23.05-SNAPSHOT
          # - octeontx-generic-23.05-SNAPSHOT
          # - layerscape-armv8_64b-23.05-SNAPSHOT
          # - armsr-armv8-23.05-SNAPSHOT
          # - bcm27xx-bcm2708-23.05-SNAPSHOT
          # - arm_arm1176jzf-s_vfp-23.05-SNAPSHOT
          # - sifiveu-generic-23.05-SNAPSHOT
          # - riscv64_riscv64-23.05-SNAPSHOT
          # - zynq-generic-23.05-SNAPSHOT
          # - imx-cortexa9-23.05-SNAPSHOT
          # - arm_cortex-a9_neon-23.05-SNAPSHOT
          # - mxs-generic-23.05-SNAPSHOT
          # - at91-sam9x-23.05-SNAPSHOT
          # - arm_arm926ej-s-23.05-SNAPSHOT
          # - at91-sama7-23.05-SNAPSHOT
          # - octeon-generic-23.05-SNAPSHOT
          # - apm821xx-sata-23.05-SNAPSHOT
          # - apm821xx-nand-23.05-SNAPSHOT
          # - powerpc_464fp-23.05-SNAPSHOT
          # - tegra-generic-23.05-SNAPSHOT
          # - mvebu-cortexa9-23.05-SNAPSHOT
          # - mpc85xx-p2020-23.05-SNAPSHOT
          # - mpc85xx-p1020-23.05-SNAPSHOT
          # - mpc85xx-p1010-23.05-SNAPSHOT
          # - powerpc_8548-23.05-SNAPSHOT
          # - oxnas-ox820-23.05-SNAPSHOT
          # - arm_mpcore-23.05-SNAPSHOT
          # - sunxi-cortexa7-23.05-SNAPSHOT
          # - mediatek-mt7623-23.05-SNAPSHOT
          # - layerscape-armv7-23.05-SNAPSHOT
          # - ipq40xx-chromium-23.05-SNAPSHOT
          # - ipq40xx-generic-23.05-SNAPSHOT
          # - imx-cortexa7-23.05-SNAPSHOT
          # - bcm27xx-bcm2709-23.05-SNAPSHOT
          # - x86-geode-23.05-SNAPSHOT
          # - x86-legacy-23.05-SNAPSHOT
          # - i386_pentium-mmx-23.05-SNAPSHOT
          # - sunxi-cortexa8-23.05-SNAPSHOT
          # - arm_cortex-a8_vfpv3-23.05-SNAPSHOT
          # - mvebu-cortexa72-23.05-SNAPSHOT
          # - bcm27xx-bcm2711-23.05-SNAPSHOT
          # - ipq806x-chromium-23.05-SNAPSHOT
          # - ipq806x-generic-23.05-SNAPSHOT
          # - pistachio-generic-23.05-SNAPSHOT
          # - realtek-rtl838x-23.05-SNAPSHOT
          # - kirkwood-generic-23.05-SNAPSHOT
          # - arm_xscale-23.05-SNAPSHOT
          # - gemini-generic-23.05-SNAPSHOT
          # - arm_fa526-23.05-SNAPSHOT
          # - bcm47xx-mips74k-23.05-SNAPSHOT
          # - bcm53xx-generic-23.05-SNAPSHOT
          # - armvirt-32-23.05-SNAPSHOT
          # - armvirt-64-23.05-SNAPSHOT
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build ispappd-${{ matrix.arch }}
        uses: kmoz000/gh-action-sdk@main
        continue-on-error: false
        env:
          NO_REFRESH_CHECK: true
          # NO_DEFAULT_FEEDS: true
          IGNORE_ERRORS: false
          FEEDNAME: ispappd
          FEED_DIR: ${{ github.workspace }}/feeds/
          GOPACKAGELATEST: true
          ARCH: ${{ matrix.arch }}
          PACKAGES: goispappd
          V: s
        
      - name: Store packages
        uses: ncipollo/release-action@v1
        # env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowUpdates: true
          replacesArtifacts: true
          artifacts: |
            bin/packages/**/goispappd/*.ipk
            bin/packages/**/goispappd/*.apk
          tag: ${{ matrix.arch }}
      - name: Create directory for R2 upload
        run: mkdir -p r2-upload/packages/${{ matrix.arch }}
      - name: Move packages to R2 upload directory
        continue-on-error: true
        run: |
          if ls bin/packages/**/goispappd/*.ipk 1> /dev/null 2>&1; then
            cp bin/packages/**/goispappd/*.ipk r2-upload/packages/${{ matrix.arch }}/
          fi
          if ls bin/packages/**/goispappd/*.apk 1> /dev/null 2>&1; then
            cp bin/packages/**/goispappd/*.apk r2-upload/packages/${{ matrix.arch }}/
          fi
      - name: Upload to Cloudflare R2
        continue-on-error: true
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: r2-upload/packages/
          destination-dir: goispappd/builds/${{ github.run_number }}/${{ matrix.arch }}/
          output-file-url: true
          multipart-concurrent: true
