name: Release OpenWrt Package

on:
  push:
    tags:
      - 'v*.*.*'
permissions:
  contents: write
jobs:
  release-source-tarball:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create source tarball (ispappd folder)
        run: |
          VERSION=$(echo ${{ github.ref }} | sed 's|refs/tags/||')
          tar --exclude-vcs -czf ispappd-$VERSION.tar.gz -C ispappd . --transform "s,^,ispappd-$VERSION/,"
          tar --exclude-vcs -czf goispappd-$VERSION.tar.gz -C goispappd . --transform "s,^,goispappd-$VERSION/,"

      - name: Generate SHA256 hash for tarball
        run: |
          VERSION=$(echo ${{ github.ref }} | sed 's|refs/tags/||')
          sha256sum ispappd-$VERSION.tar.gz > ispappd-$VERSION.tar.gz.sha256
          sha256sum goispappd-$VERSION.tar.gz > goispappd-$VERSION.tar.gz.sha256

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            ispappd-${{ github.ref_name }}.tar.gz
            ispappd-${{ github.ref_name }}.tar.gz.sha256
            goispappd-${{ github.ref_name }}.tar.gz
            goispappd-${{ github.ref_name }}.tar.gz.sha256
